/****************************************Copyright (c)***************************************************
 **                      JUNPENG Easivend Co.,Ltd.
 **                               http://www.easivend.com
 **-------------------------------------File Info--------------------------------------------------------
 ** @Filename:			MOTOR.H
 ** @brief:				The original version  
 ** @CreatedBy:			sunway 
 ** @CreatedDate:		2016-07-01
 ** @Version:			V1.0      
 *******************************************************************************************************/
#ifndef _MOTOR_H
#define _MOTOR_H

void MOTORInit(void);
unsigned char MotorVending(unsigned int channel);

#endif
/**************************************End Of File*******************************************************/
